name: Bug Report
description: Report an issue with Valetudo+
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please [request them here instead][fr].

        [fr]: https://github.com/Algid/Valetudo-plus/discussions
  - type: textarea
    id: what-is-happening
    attributes:
      label: What is happening?
      description: What behavior do you observe?
    validations:
      required: true



  - type: textarea
    id: what-should-be-happening
    attributes:
      label: What should be happening?
      description: |
        What would be the correct behavior?
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: valetudo-version
    attributes:
      label: Please enter the Valetudo+ version you're using
    validations:
      required: true

  - type: input
    id: robot
    attributes:
      label: Please enter the vendor and model of robot you're using
    validations:
      required: true

  - type: input
    id: robot-firmware
    attributes:
      label: Please enter the robot's firmware version you're using
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Anything else relevant to the situation.<br/>
        Think: Browser, Phone, Home Assistant version, Wi-Fi access points, Etc.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots here

